import Head from "next/head";

import Banner from "../components/banner/Banner";
import Navbar from "../components/nav/NavBar";
import Card from "../components/card/Card";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar username="amir@gmail.com" />
      <Banner
        title="childford a red dog"
        subTitle="a very butifull dog"
        imgUrl="/static/clifford.webp"
      />
      <Card imgUrl="/static/clifford.webp" size="larg" />
      <Card imgUrl="/static/clifford.webp" size="medium" />
      <Card imgUrl="/static/clifford.webp" size="small" />
    </div>
  );
}
