import Head from "next/head";

import Banner from "../components/banner/Banner";
import Navbar from "../components/nav/NavBar";
import SectionCard from "../components/card/SectionCard";
import { getVideos } from "../lib/videos";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  const disneyVideos = await getVideos();
  return {
    props: { disneyVideos },
  };
}

export default function Home({ disneyVideos }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar username="amir@gmail.com" />
      <Banner
        title="childford a red dog"
        subTitle="a very butifull dog"
        imgUrl="/static/clifford.webp"
      />
      <div className={styles.sectionWrapper}>
        <SectionCard title="Disney" videos={disneyVideos} size="larg" />
      </div>
      <div className={styles.sectionWrapper}>
        <SectionCard title="Disney" videos={disneyVideos} size="medium" />
      </div>
    </div>
  );
}
